"""
pinecone_manager.py

Handles all Pinecone operations:
- Connect to Pinecone
- Create index
- Get index
- Upload vectors
- Prepare vectors
- View index statistics
"""

import os
from dotenv import load_dotenv
from pinecone import Pinecone, ServerlessSpec

load_dotenv()

# -------------------- CONSTANTS -------------------- #

INDEX_DIMENSION = 768
METRIC = "cosine"
CLOUD = "aws"
REGION = "us-east-1"


class PineconeManager:
    """Manage all Pinecone operations."""

    def __init__(self):
        self.api_key = os.getenv("PINECONE_API_KEY")
        self.index_name = os.getenv("PINECONE_INDEX")

        if not self.api_key:
            raise ValueError("PINECONE_API_KEY not found in .env")

        if not self.index_name:
            raise ValueError("PINECONE_INDEX not found in .env")

        self.client = Pinecone(api_key=self.api_key)

    # ------------------------------------------------ #

    def create_index(self):
        """
        Create the Pinecone index if it doesn't exist.
        """

        indexes = self.client.list_indexes().names()

        if self.index_name in indexes:
            return "Index already exists"

        self.client.create_index(
            name=self.index_name,
            dimension=INDEX_DIMENSION,
            metric=METRIC,
            spec=ServerlessSpec(
                cloud=CLOUD,
                region=REGION
            )
        )

        return "Index created successfully"

    # ------------------------------------------------ #

    def get_index(self):
        """
        Return the Pinecone index.
        """

        return self.client.Index(self.index_name)

    # ------------------------------------------------ #

    def list_indexes(self):
        """
        Return all available indexes.
        """

        return self.client.list_indexes().names()

    # ------------------------------------------------ #

    def prepare_vectors(self, chunks, embeddings):
        """
        Prepare vectors for Pinecone upload.

        Parameters
        ----------
        chunks : list
            Document chunks.

        embeddings : list
            Embedding vectors generated by AI module.

        Returns
        -------
        list
            Pinecone-compatible vectors.
        """

        vectors = []

        for chunk, embedding in zip(chunks, embeddings):

            vectors.append({

                "id": chunk.metadata["chunk_id"],

                "values": embedding,

                "metadata": {

                    "source": chunk.metadata["source"],

                    "page": chunk.metadata["page"],

                    "chunk_number": chunk.metadata["chunk_number"],

                    "characters": chunk.metadata["characters"],

                    "words": chunk.metadata["words"],

                    "text": chunk.page_content

                }

            })

        return vectors

    # ------------------------------------------------ #

    def upsert_vectors(self, vectors):
        """
        Upload vectors to Pinecone.
        """

        if not vectors:
            return 0

        index = self.get_index()

        index.upsert(vectors=vectors)

        return len(vectors)

    # ------------------------------------------------ #

    def get_index_stats(self):
        """
        Return index statistics.
        """

        index = self.get_index()

        return index.describe_index_stats()

    # ------------------------------------------------ #

    def delete_all_vectors(self):
        """
        Delete all vectors from the index.
        """

        index = self.get_index()

        index.delete(delete_all=True)